version: "3"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: kBxQltLZGPvRIBcHmtOH
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: r4osO3YeW1*Vae8GY6#L
      DATABASE_HOST: postgres
    volumes:
      - pddata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadming:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5500:80
    networks:
      - postgres
    restart: unless-stopped


volumes:
  pddata:
  pgadmin:

networks:
  postgres:
    driver: bridge
